
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import project.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class adminHome extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
    }

    
    
    //capitalizing each first word
       
       public static String  capitalize(String str)
       {
         String words[]=str.split("\\s");  //array
    String capitalizeWord="";  
    for(String w:words){  
        String first=w.substring(0,1);  //capitalize first character of each word
        String afterfirst=w.substring(1);  
        capitalizeWord+=first.toUpperCase()+afterfirst+" ";  
       }
      
    return capitalizeWord.trim();  
       }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("WELCOME ADMIN !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 31, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1191, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search By Name or Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 143, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 140, 250, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 139, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1247, 139, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Security Question", "Address", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 203, 1250, 552));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin Home.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1440, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // when logout  button pressed by admin from adminHome page
        int a;
        //shows confirmation dialog yes(0) ,no(1)
        a= JOptionPane.showConfirmDialog(null, "Do you really want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        //checking what admin pressed
        if(a==0)
        {//when admin press yes(0) then
            setVisible(false);//making this page invisible
            new login().setVisible(true);//making login page visble
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // when exit button pressed by admin from adminHome page
        int a;
        //shows confirmation dialog yes(0) ,no(1)
        a= JOptionPane.showConfirmDialog(null, "Do you really want to Close Application ?","Select",JOptionPane.YES_NO_OPTION);
        //checking what admin pressed
        if(a==0)
        {//when admin press yes(0) then
            System.exit(0);//JVM stopp working and application is exit
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       //for receive email or name to be search that email come here from adminHome page form
       if(!(Pattern.matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$",jTextField1.getText())))
                 {
                 JOptionPane.showMessageDialog(null,"Enter Valid Email !","Error",JOptionPane.ERROR_MESSAGE);
                 }
                 else{
       String email = jTextField1.getText();
         String name = capitalize(jTextField1.getText());  
       
//for retriving multiple data from table through  SelectForLogin method for execution  in  SelectForLogin and writing query
        ResultSet rs = SelectForLogin.getData("Select * from users where name like '%"+name+"%' or email like '%"+email+"%' ");
        //for displaying data in a table for that we have to write
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();//creating object-> model for jtable1 and getting model
        
          //to delete rows we are writing this code->
          model.setRowCount(0);
          
          try
          {//value in table filled here from database hotel
              while(rs.next())
              {//loop execute untill we receive values from databse from table users
                  //setting values in table row wise 
                  model.addRow(new Object[]
                  {
                      rs.getString(1),//column1 is name in database hotel->table users
                       rs.getString(2),//column2 is email in database hotel->table users
                        rs.getString(4),//column4 is securityQuestion in database hotel->table users
                         rs.getString(6),//column6 is address in database hotel->table users
                          rs.getString(7)//column7 is status in database hotel->table users
                  });
                  
              }
          
                        rs.close();//closing ResultSet
          }
          catch(Exception e)
          {//when error show it
          JOptionPane.showMessageDialog(null, e);
          }   
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //click on table in design view then  go to window click on navigator select jframe(right click select event) ->component->componentshow(click)
        //showing data on table from database hotel
        //import project package and java.sql all class
        
        //for retriving multiple data from table through  SelectForLogin method for execution  in  SelectForLogin and writing query
        ResultSet rs = SelectForLogin.getData("Select * from users");
        //for displaying data in a table for that we have to write
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();//creating object-> model for jtable1 and getting model
        
          //to delete rows we are writing this code->
          model.setRowCount(0);
          
          try
          {//value in table filled here from database hotel
              while(rs.next())
              {//loop execute untill we receive values from databse
                  //setting values in table row wise 
                  model.addRow(new Object[]
                  {
                      rs.getString(1),//column1 is name in database hotel->table users
                       rs.getString(2),//column2 is email in database hotel->table users
                        rs.getString(4),//column4 is securityQuestion in database hotel->table users
                         rs.getString(6),//column6 is address in database hotel->table users
                          rs.getString(7)//column7 is status in database hotel->table users
                  });
                  
              }
          
                        rs.close();//closing ResultSet
          }
          catch(Exception e)
          {//when error show it
          JOptionPane.showMessageDialog(null, e);
          }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // when clear button is pressed from adminHome page then
          setVisible(false);//making this page invisible
            new adminHome().setVisible(true);//making adminHome() page visble
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // click on table ->rightclick(choose event)->select mouse ->click on mouseclicked 
        int index;
        //mouse clicked row index value selected from table1
        index=jTable1.getSelectedRow();
        //import TableModel then declare object for that table
        TableModel model = jTable1.getModel();
        //declaring variable and taking value from selected row and column , note:column 0-so on from table
        String email = model.getValueAt(index, 1).toString();//email is at column 1 in table
         String status = model.getValueAt(index, 4).toString();//status is at column 4 in table
         
         //checking the status and changing true to false and vice versa
         if(status.equals("true"))
         {
           status="false";
         }
         else
         {
           status="true";
         }
         //
        try
        {//showing confirmation message to change status in database
            int a;
           a= JOptionPane.showConfirmDialog(null,"Do you really want to change status","Select",JOptionPane.YES_NO_OPTION);
            //checking admin selected yes(0) or no(1)
           if(a==0)
           {//changing status in database by InsertUpdateDelete(Query,msg) method in  InsertUpdateDelete class in project
               InsertUpdateDelete.setData("update users set status='"+status+"' where email='"+email+"'", "Status Changed Successfully!");
               //making this page invisible
              setVisible(false);
              //making this page visible again as refresh
              new adminHome().setVisible(true);
           }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
