/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.*;
import java.text.ParseException ;
//for pdf genertion and writing on it
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
import java.io.FileOutputStream;
/**
 *
 * @author Dell
 */
public class customerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckOut
     */
    public customerCheckOut() {
        initComponents();
        //making received data from databse table customer,room in a customerCheckOut form variable eneditable
        //jTextField1.setEditable(false);//room number
        jTextField2.setEditable(false);//name 
        jTextField3.setEditable(false);//check in date
        jTextField4.setEditable(false);//checkoutdate
        jTextField5.setEditable(false);//mobile number
        jTextField6.setEditable(false);//email
        jTextField7.setEditable(false);//price per day
        jTextField8.setEditable(false);//number of days stayed
        jTextField9.setEditable(false);//payable amount
    }
      //declaring variable to store value from form customerCheckOut
     int id=0;
     String roomType;
     String bed;
     String roomNo;
     String Query;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 13, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 30, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 81, 116, -1));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 84, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", " Name", "Mobile ", "Nationality", "Gender", "Email", "ID Proof", "Address", "Check In Date", "Room number", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 1167, 242));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 129, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 153, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 129, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 153, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Check Out Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 129, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 153, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 129, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 153, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 211, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 248, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price Per Day");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 211, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 248, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Number Of Days Stayed");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 211, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 248, 250, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Amount To Be Collected");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 211, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 248, 250, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 302, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 302, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          // when clear button is pressed from customerCheckOut form page then
          setVisible(false);//making this page invisible
            new customerCheckOut().setVisible(true);//making customerCheckOut() page visble
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //exit button from customerCheckOut form
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // getting all data from database customer table who are not checkout ie:checkout date is null
        String Query="select * from customer where checkOut is NULL";
        ResultSet rs=SelectForLogin.getData(Query);
        
        //putting these data in table present in customerCheckOut table
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();//creating object for table
        try
        {
           while(rs.next())
           {//when any value received then
               //adding row in table
               model.addRow(new Object[]{//putting data in column wise 
                        rs.getString(1),//id from db table customer into customerCheckIn table
                         rs.getString(2),//name
                          rs.getString(3),//mobilenumber
                           rs.getString(4),//nationality
                            rs.getString(5),//gender
                             rs.getString(6),//email
                              rs.getString(7),//idproof
                               rs.getString(8),//address
                                rs.getString(9),//checkin date
                                 rs.getString(10),//room number
                                  rs.getString(11),//bed
                                   rs.getString(12),//roomType
                                    rs.getString(13),//pricePerDay
                                     
                                        });
           }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // when search button is click from customerCheckOut then roomNo received here
        String roomNo =jTextField1.getText();
        try
        {//running querry to retrive data from database table customer
        String Query ="select * from customer where roomNo='"+roomNo+"' and checkOut is NULL";
        ResultSet rs=SelectForLogin.getData(Query);
          if(rs.next())
          {//when any data received then showing in text fields in customerCheckOut form
             jTextField2.setText(rs.getString(2)); //name
             jTextField3.setText(rs.getString(9)); //in day
           //jTextField4.setText(rs.getString(4));  //out day
             jTextField5.setText(rs.getString(3)); //mobilr
             jTextField6.setText(rs.getString(6));  //email
             jTextField7.setText(rs.getString(13));  //price per day
           //jTextField8.setText(rs.getString(8));  //total day stayed
           //jTextField9.setText(rs.getString(9));  //amount to be paid
           
           //for getting checkOutday(today)
           //create object for dateformat import simpledatetformat
           //SimpleDateFormat myFormat = new SimpleDateFormat("EE MMM dd HH:mm:ss z yyyy");
           
           /*The java.text.SimpleDateFormat class provides methods to format and parse date and time in java.
           The SimpleDateFormat is a concrete class for formatting and parsing date which inherits java.text.
           DateFormat class.*/
          SimpleDateFormat myFormat =new SimpleDateFormat("yyyy/MM/dd");
           //create object for todaydate import calender utility
           Calendar cal=Calendar.getInstance();
           //putting checkoutdate in form customerCheckOut in jTextField4,(object.format)formating date to string
           jTextField4.setText(myFormat.format(cal.getTime()));
           
           //calculation in days =diffrence between check in and check out
           //Note:One day Time in ms (milliseconds) var one_day = 1000 * 60 * 60 * 24 and parse convert string to date format
            String beforeDate1 = rs.getString(9);//getting date and
            //Notice that formatting means converting date to string and parsing means converting string to date.
            java.util.Date beforeDate2 = myFormat.parse(beforeDate1); // convert string to date format
            
            //(object.format)formating date to string
            String afterDate1 =myFormat.format(cal.getTime());//getting date (today)
            //(object.parse)parsing string to date
            java.util.Date afterDate2 = myFormat.parse(afterDate1); // convert string to date format
            
            //difference in date in millisecond also get date & time in milliseconds
              long difference=afterDate2.getTime()-beforeDate2.getTime();
              //converting difference in days
              int noOfDaysStay=(int)(difference/(1000*60*60*24));
              //putting checkoutdate in form customerCheckOut in jTextField8
               
           //after divide if difference is 0 ie:same then no of day=1
              if(noOfDaysStay==0)
                noOfDaysStay=1;
              jTextField8.setText(String.valueOf(noOfDaysStay));
              
              //getting pricePerDay in string from form customerCheckOut converting string to float
             float price=Float.parseFloat(jTextField7.getText());
             
              //displaying total amount payable by customer
             jTextField9.setText(String.valueOf(noOfDaysStay*price));
          }else
          {
            JOptionPane.showMessageDialog(null, "ROOM Number Is Not Booked or Does Not Exist!");
          }
        
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null, e);
                  
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //when check out button is pressed from customerCheckOut form then
       //all data from form retrived here 
        String roomNo = jTextField1.getText();
        String name = jTextField2.getText();
        String checkIn = jTextField3.getText();
        String checkOut = jTextField4.getText();
        String mobileNo = jTextField5.getText();
        String email = jTextField6.getText();
        String pricePerDay = jTextField7.getText();
        String numberOfDaysStay = jTextField8.getText();
        String amountPayable = jTextField9.getText();
        try{
        //running querry to get data from customer table
         Query ="select * from customer where roomNo='"+roomNo+"' and email='"+email+"' and checkIn='"+checkIn+"' and mobileNumber='"+mobileNo+"' and name='"+name+"' ";
        ResultSet rs=SelectForLogin.getData(Query);
         if(rs.next())
         {
        
        
        String     id = rs.getString(1);
        String roomType=rs.getString(12);
        String bed=rs.getString(11);
          //runnung query to update customer table  in database set checkout Date ,noOfDaysStay,totalAmount
        String Query="update customer set numberOfDaysStay='"+numberOfDaysStay+"',checkOut= '"+checkOut+"',totalAmount='"+amountPayable+"' where id='"+id+"'";
        InsertUpdateDelete.setData(Query, "");
        
          //runnung query to update room table  in database set roomStatus to Not Booked
         Query="update room set roomStatus='Not Booked' where roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
         }
         else
         {
          JOptionPane.showMessageDialog(null, "Room number doesnot Exists!");
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
        
        //Now obtaining Print pdf Bill for Customer add jar file "itextpdf"
         String path ="D:\\";//in D drive pdf is store
         //importing com.itextpdf.text.Document create doc object
              //or write-> com.itextpdf.text.Document doc= new com.itextpdf.text.Document();  
              Document doc = new Document();
         try
         {
           Query ="select * from customer where roomNo='"+roomNo+"' and email='"+email+"' and checkIn='"+checkIn+"' and mobileNumber='"+mobileNo+"' and name='"+name+"' ";
        ResultSet rs=SelectForLogin.getData(Query); 
         if(rs.next())
         {
        
        
        String     id = rs.getString(1);
        String roomType=rs.getString(12);
        String bed=rs.getString(11);
           
           //import com.itextpdf.text.pdf.PdfWriter
            PdfWriter.getInstance(doc , new FileOutputStream(path+""+id+".pdf"));
            doc.open();
             
             //import com.itextpdf.text.Pragraph  ;  
              //creating obj for imported class Paragraph then write things you want to write in it
              Paragraph para1 = new Paragraph("NANC HOTEL BHIRAHAWA\n\n\n");
             //import com.itextpdf.text.Element and setting text in center ;
            para1.setAlignment(Element.ALIGN_CENTER);
             //adding text in pdf document
            doc.add(para1);
                 
            Paragraph para2 = new Paragraph("**************************************************************************************************************\n\n");
            doc.add(para2);
                 
            Paragraph para3 = new Paragraph("\tBill ID: "+id+"\nCustomer Details:\nName: "+name+"\nMobile number: "+mobileNo+"\nEmail: "+email+"\n");
            doc.add(para3);
            //putting ***again so adding  doc.add(para2);
            doc.add(para2);
            
            Paragraph para4 = new Paragraph("\tRoom Details:\nNumber: "+roomNo+"\nType: "+roomType+"\nBed: "+bed+"\nPrice per day: "+pricePerDay+"\n");
            doc.add(para4);
            //putting ***again so adding  doc.add(para2);
            doc.add(para2);
            
            //adding table so import com.itextpdf.text.pdf.PdfPTable; and create object for it
            PdfPTable tb1=new PdfPTable(4) ;//4 column needed in table
            tb1.addCell("Check In Date: "+checkIn);
            tb1.addCell("Check Out Date: "+checkOut);
            tb1.addCell("No Of Days Stayed: "+numberOfDaysStay);
            tb1.addCell("Total Amount Paid: "+amountPayable);
            doc.add(tb1);//adding this column in table
           doc.add(para2);
           Paragraph para5 = new Paragraph("\t\n\n\nSignature Cashier\n\n");
           para5.setAlignment(Element.ALIGN_RIGHT);
            doc.add(para5);
            //putting ***again so adding  doc.add(para2);
            doc.add(para2);
           //writing please visit again
            Paragraph para6 = new Paragraph("\nThankYou ,Please Visit Again!");
            para6.setAlignment(Element.ALIGN_CENTER);
            doc.add(para6);
         }
         else
         {
          JOptionPane.showMessageDialog(null, "Room number doesnot Exists!");
         }
         }
         catch(Exception e)
         {
           JOptionPane.showMessageDialog(null, e);
         }
         
         //closing doc
            doc.close();
         
         //asking whether want print document or not 
        int a= JOptionPane.showConfirmDialog(null, "Do you want to Print Bill?","Select",JOptionPane.YES_NO_OPTION);
         //checking what user press yes(0) or no(1)
         if(a==0)
         {
         //when yes option is clicked
             try
             {//calling that pdf by id.pdf
                 if((new File("D:\\"+id+".pdf")).exists())//check whether by by id.pdf present in D drive or not ,import java.io.File
                 {
                   Process p=Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler E:\\"+id+".pdf ");
                 }
                 else
                 {
                 System.out.println("File Does Not Exists!");
                 }
             }
             catch(Exception e)
             {
             JOptionPane.showMessageDialog(null, e);
             }
         }
         
        setVisible(false);
        new customerCheckOut().setVisible(true);
         
    }//GEN-LAST:event_jButton3ActionPerformed

    /**}
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
